{% set name = "cronsim" %}
{% set version = "2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cronsim-{{ version }}.tar.gz
  sha256: 5aab98716ef90ab5ac6be294b2c3965dbf76dc869f048846a0af74ebb506c10d

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  imports:
    - cronsim
  commands:
    - pip check
  requires:
    - pip
    - python

about:
  home: https://github.com/cuu508/cronsim
  summary: Cron expression parser and evaluator
  description: Cron Sim(ulator), a cron expression parser and evaluator.
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  dev_url: https://github.com/cuu508/cronsim
  doc_url: https://github.com/cuu508/cronsim/blob/main/README.md

extra:
  recipe-maintainers:
    - apmorton
