{% set name = "cronsim" %}
{% set version = "2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cuu508/cronsim/archive/refs/tags/{{ version }}.tar.gz
  sha256: 9ae51c8567bfd9375b313d08c9307f7417ab7e7ff935914546a189f4c416c683

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  imports:
    - cronsim
  commands:
    - pip check
  requires:
    - pip
    - python

about:
  home: https://github.com/cuu508/cronsim
  summary: Cron expression parser and evaluator
  description: Cron Sim(ulator), a cron expression parser and evaluator.
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  dev_url: https://github.com/cuu508/cronsim
  doc_url: https://github.com/cuu508/cronsim/blob/main/README.md

extra:
  recipe-maintainers:
    - apmorton
